# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
    ]
