# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_resource_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='order_by',
            field=models.IntegerField(default=0),
        ),
    ]
