# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_resourcetype_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='mime_type',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
